insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("LG그램", "notebook", 150, "LG전자", 150, "가벼운 LG그램")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("맥북", "notebook", 300, "애플", 300, "성능 좋은 맥북")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("삼성노트북9", "notebook", 200, "삼성전자", 200, "삼성의 노트북")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("에어팟", "Earbuds", 20, "애플", 20, "무선이어폰 에어팟")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("버즈", "Earbuds", 10, "삼성전자", 10, "무선이어폰 버즈")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("갤럭시노트10", "phone", 50, "삼성전자", 50, "삼성의 갤럭시 노트10")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("아이폰XS", "phone", 100, "애플", 100, "애플의 아이폰XS")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("에어맥스", "shoes", 10, "나이키", 100, "나이키 운동화 에어맥스")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("슈퍼스타", "shoes", 10, "아디다스", 100, "아디다스 운동화 슈퍼스타")
insert into product_table(name, category, price, manufacturer, unitinstock, description) values ("올스타", "shoes", 8, "컨버스", 100, "컨버스 올스타")
